### ISSUE TITLE
Device discovered but no display shown

### ISSUE THREAD

**Issue by birep** [MajeurAndroid/Adb-Remote-Screen#12]
Running on Ubuntu. The device is found but not displayed on my computer, and attempting to save a screenshot results in an empty file.

Terminal exception: 
```
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1315)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.majeur.ars.ScreenPanel$UpdateThread.repaintPanel(ScreenPanel.java:238)
	at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:222)
```
And the log file:
```
1:44:30.298	INFO: Adb path used: /usr/bin/adb
1:44:30.868	INFO: Connected devices changed
1:44:30.870	INFO: Start rendering device screen
1:44:37.931	INFO: Stop rendering device screen
```
Anything else I can do to get you more info? Thank you!

**Comment by birep** [comment]
Just realized this is a dup of #9
