### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by maemolol** [MajeurAndroid/Adb-Remote-Screen#20]
So, to explain the situation, I run a fresh installation of Ubuntu 21.04, but I have installed Java. Whenever I try to launch it through the terminal, it spews out:
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-17-openjdk-amd64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:310)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:280)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2392)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1387)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1386)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1419)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1313)
	at com.majeur.ars.AdbRemoteScreen.main(AdbRemoteScreen.java:27)

What do I do?

**Comment by Alex-Beh** [comment]
Hey, you can try run the following command to install the dependencies.
`sudo apt install openjdk-13-jre-headless`

**Comment by maemolol** [comment]
uhh, it's been 6 months, i'm an arch user now
