### ISSUE TITLE
Getting a java.lang.InterruptedException

### ISSUE THREAD

**Issue by stam** [MajeurAndroid/Adb-Remote-Screen#9]
I am connecting a Sony Xperia Z5 compact to my macbook and I am running AdbRemoteScreen using the terminal.
 
The screen does not render, the terminal shows:
```
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1315)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.majeur.ars.ScreenPanel$UpdateThread.repaintPanel(ScreenPanel.java:238)
	at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:222)
```

The log shows this:
```
11:31:01.272	INFO: Adb path used: /usr/local/bin/adb
11:31:03.524	INFO: Connected devices changed
11:31:03.526	INFO: Start rendering device screen
11:31:04.172	INFO: Stop rendering device screen
11:31:15.744	INFO: Start rendering device screen
11:31:16.378	INFO: Stop rendering device screen
11:31:20.215	INFO: Start rendering device screen
11:31:20.843	INFO: Stop rendering device screen
```
The command I run is this:
`java -jar AdbRemoteScreen.jar /usr/local/bin/adb`

**Comment by parkerlreed** [comment]
Same here on a Nexus 5X on Oreo. Both fast updates set to true and false throw the same error.

**Comment by GordonHannan** [comment]
I am getting the same error as well on a Zebra TC8000 running Android 5.1.1. The screen doesn't render, but the button commands seem to send though. Any ideas?


Command run:
` java -jar AdbRemoteScreen.jar "/c/Program Files/Google/android-platform-tools/adb.exe"`

Output:
```
Exception in thread "Thread-4" java.lang.ExceptionInInitializerError
        at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at com.majeur.ars.Utils.getRunningJarPath(Utils.java:23)
        at com.majeur.ars.LocalProperties.<clinit>(LocalProperties.java:21)
        ... 1 more
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
        at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
        at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: Could not initi
alize class com.majeur.ars.LocalProperties
        at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
Exception in thread "Thread-9" java.lang.NoClassDefFoundError: Could not initialize class com.majeur.ars.LocalProperties
        at com.majeur.ars.ScreenPanel$UpdateThread.run(ScreenPanel.java:214)
```

Console log:
```
11:51:10.489	INFO: Adb path used: C:/Program Files/Google/android-platform-tools/adb.exe
11:51:11.480	INFO: Connected devices changed
11:51:11.481	INFO: Start rendering device screen
11:54:31.152	INFO: Start rendering device screen
11:54:31.152	INFO: Stop rendering device screen
```

**Comment by voidplayer** [comment]
Can confirm that PR #11 fixes the issue

**Comment by MajeurAndroid** [comment]
Use of `perl chomp` has been removed.
